# Generated by Django 5.0.8 on 2025-10-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='password',
            field=models.CharField(default='temp123', max_length=128),
            preserve_default=False,
        ),
    ]
