# Generated by Django 5.0.8 on 2025-10-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_donor_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='recipient',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='donor',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
