# Generated by Django 5.0.8 on 2025-10-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ngo_password_recipient_password_alter_donor_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngo',
            name='password',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='password',
        ),
        migrations.AlterField(
            model_name='donor',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
